### ISSUE TITLE
Test new release of RTM

### ISSUE THREAD

**Issue by rinrincodes** [rinrincodes/mcla-respack#12]
RTM just got updated to 2.4.5. I've got the files but it still needs to be tested. From what I've heard it may crash for a few people but idk till we try.

**Comment by rinrincodes** [comment]
Oops meant to put this in the modpack repo. Oh well!

**Comment by hawka97** [comment]
[UPDATE] A commit has been pushed in relation to this issue. This issue will now be closed. Please follow hawka97/mcla-modpack for updates.
