### ISSUE TITLE
Increase rendering distance

### ISSUE THREAD

**Issue by rinrincodes** [rinrincodes/mcla-respack#13]
The rendering distance is set very low on normal. Setting it to far+ will be better for most users as there won't be as much constant chunk loading in the background.

**Comment by rinrincodes** [comment]
Oops meant to put this in the modpack repo. Oh well!

**Comment by hawka97** [comment]
[UPDATE] A commit has been pushed in relation to this issue. This issue will now be closed. Please follow hawka97/mcla-modpack for updates.
