### ISSUE TITLE
Migrate Life Safety Devices from Res Pack to ModDev Life Safety Mod

### ISSUE THREAD

**Issue by hawka97** [rinrincodes/mcla-respack#14]
Textures have been created for this and are on git. This mod needs to be worked on ASAP. It can be done in MCCREATOR since it's a simple mod mostly

**Comment by rinrincodes** [comment]
All files are already in the moddev repo with all of them already optimized with a small handful that still need to be optimized. As for Mcreator, I'm not going to be using it for this mod and with any other mods I make/work on as I'd prefer to write it from scratch in Eclipse just for the bounding boxes issues and for having larger bounding boxes that Mcreator simply won't do. Also from what I've heard with Mcreator it handles global variables in a very weird and odd way and is still quite clunky to use. Please don't ask about Mcreator anymore as I'm trying my hardest to depart from it and make a few "real" mods for once.

**Comment by rinrincodes** [comment]
As for all Mcreator files all the Mcreator backup archives have been removed from the repo so you can't use them to work on Essentials and Roads in Mcreator anymore. I'm also going to be in the progress of cleaning up the entire moddev repo to move a lot of the files around when everything gets migrated/worked on in Eclipse for future mod dev.
